### ISSUE TITLE
WindowLeak - exit app and got window leak.

### ISSUE THREAD

**Issue by ryc16** [NathanWalker/nativescript-loading-indicator#16]
Hi @NathanWalker, 

My app got windowleak and I took some times to find there is a windowleak to your plugin. The leak is due to progressDialog never called dismiss. Below is just a _working_ solution but it is not necessary the right place to add as hide is hide. It is not to dismiss on hide but you are dereferencing already on hide. So I think let you decide the best solution for hide and dismiss.

```
   public hide() {
        if (this._progressDialog !== undefined) {
            this._progressDialog.hide(); // hide() is from android.app.Dialog
            this._progressDialog.dismiss();
        }
        this._progressDialog = undefined;
    }
```

**Comment by NathanWalker** [comment]
@ryc16 Thanks for heads up! I like your suggested fix actually, makes sense there.
Just published `2.2.1`, hope that does it for ya 👍
