### ISSUE TITLE
utils.ios.getter is not a function

### ISSUE THREAD

**Issue by terreb** [NathanWalker/nativescript-loading-indicator#17]
I get this error on starting up the app in iOS simulator in debug mode (tns debug ios):

file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:42:32: JS ERROR TypeError: utils.ios.getter is not a function. (In 'utils.ios.getter(UIApplication, UIApplication.sharedApplication)', 'utils.ios.getter' is undefined)

My config:
nativescript cli: 2.3.0
tns-core-modules: 2.2.1
tns-ios: 2.3.0
nativescript-loading-indicator: 2.2.1
iOS 9.3 simulator
xCode 7.3.1

**Comment by bradmartin** [comment]
You need to update your core-modules I believe to `2.3.0` which is when they added this utility method to handle the iOS/Xcode8 breaking changes of methods to properties (Thank Apple 😄 )

**Comment by terreb** [comment]
Thanks @bradmartin this works:)

**Comment by terreb** [comment]
The issue can be closed then.
