### ISSUE TITLE
Is it possible to dim the background of the loader on Android?

### ISSUE THREAD

**Issue by spstratis** [NathanWalker/nativescript-loading-indicator#18]
There seems to be an option on dim the background on iOS, wondering if this is also possible on Android somehow. I've looked through some of the code and the referenced Android docs, but nothing jumps out at me that seems to allow you to do this.

**Comment by bradmartin** [comment]
The background dims for me without setting an option on Android, I just use the common options.

**Comment by spstratis** [comment]
@bradmartin Same here, I'm just curious if I can control the opacity or color of the dimming effect. Are you aware if that's possible?

**Comment by Steviey** [comment]
+1

**Comment by amirhoseindgr** [comment]
@spstratis You can change indicator color by setting  <ActivityIndicator color="blue" ></ActivityIndicator>                  
in your xml file

**Comment by Omi231** [comment]
@amirhoseindgr  how to do that?
