### ISSUE TITLE
Cancel on iOS and event when cancelling?

### ISSUE THREAD

**Issue by m-abs** [NathanWalker/nativescript-loading-indicator#20]
Two things both related to cancelling the loading-indicator.

* Is it possible to cancel the loading-indicator on iOS?
* Can I get an event/callback when it's been cancelled, so I can stop the action that triggered the loader?

Android's ProgressDialog can be initialized with a cancelListener, but I can't figure out how to set it once the dialog have been opened by this plugin.

**Comment by ryanzaatari** [comment]
Having the same issue as @m-abs, current ios specific options don't include a cancelable property.
