### ISSUE TITLE
Cannot run app from Xcode (nativescript.h) not found.

### ISSUE THREAD

**Issue by lardi** [NathanWalker/nativescript-loading-indicator#21]
Hi,
I have tried to run app from xcode and I get this message
![screen shot 2016-11-20 at 4 04 56 pm](https://cloud.githubusercontent.com/assets/3286259/20463036/bb57a6fa-af3b-11e6-8146-c30e7d4ece4d.png)

'NativeScript/NativeScript.h' file not found

**Comment by NathanWalker** [comment]
You will need to run using the `.xcworkspace` file.
