### ISSUE TITLE
Can't find variable MBProgressHUD

### ISSUE THREAD

**Issue by dsmeltz** [NathanWalker/nativescript-loading-indicator#24]
I've removed and re-added the ios platform.  
Upon building the ios platform, tns build ios, I see the dependency for MBProgressHUD being handled, and the build completes successfully.

When running the app, I receive the following error when trying to invoke the loading indicator:

EXCEPTION: Error in :0:0 caused by: Can't find variable: MBProgressHUD (/Users/administrator/Documents/near-by/node_modules/@angular/core/bundles/core.umd.js:2837:32)
ORIGINAL EXCEPTION: Can't find variable: MBProgressHUD (/Users/administrator/Documents/near-by/node_modules/@angular/core/bundles/core.umd.js:2839:36)
Dec 22 08:16:00 MBP17 nearby[2752]: CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:2837:32: EXCEPTION: Error in :0:0 caused by: Can't find variable: MBProgressHUD

**Comment by dsmeltz** [comment]
Please ignore this.  After removing and re-adding the ios platform about 6 or 7 times, getting resources to cooperate, this error no longer is being thrown.   Not sure what made it work, but it works wonderfully now.

**Comment by mmastrangelo** [comment]
The following made the error go away for me:

1. Simulator --> Reset Content and Settings in the iOS Simulator
2. Remove "platforms", "lib", and "node_modules" project subfolders
3. Rebuild/re-run
