### ISSUE TITLE
Loading Indicator Not Working

### ISSUE THREAD

**Issue by maniacube** [NathanWalker/nativescript-loading-indicator#26]
Hi,

"nativescript-loading-indicator" is not working after installing "nativescript-admob". I am not getting any errors but loading indicator is not showing. If i uninstalled the "nativescript-admob", indicator is working perfect. Please help us to resolve it.

Earlier we are posted in nativescript errors blog in github. We got the below solution from @tsonevn.

"I tested the both plugins on my side and this behavior seems to be reproduced only on iOS.
As you have mentioned, this issue has been related to nativescript-loading-indicator.
In that case, you could contract with the plugin authors and to open a new issue in its repository ."

**Comment by blaur** [comment]
And I just found out... I am experiencing the exact same issue. Everything works on Android but not on iOS due to the admob module....

More precisely I have installed: nativescript-google-mobile-ads-sdk

**Comment by blaur** [comment]
I just came to me that I did not leave much information about what I have done.

My problem has appeared after upgrading to NativeScript 2.5.1 where also Firebase had to be upgraded accordingly. After that upgrade firebase expects google mobile ads sdk and after installing that I am no longer seeing the loading indicator. No errors or anything just no loading indicator.

**Comment by blaur** [comment]
I have just confirmed by removing the admob logic out of firebase.ios.js and everything work as expected.

**Comment by maniacube** [comment]
Hi blaur, You have commented like "by removing the admob logic out of firebase.ios.js" everything is working fine. But where this file is located in project folder structure.

**Comment by blaur** [comment]
Hi @maniacube,

I am using a firebase nativescript plugin. It is this plugin that contains the option to use admob but in my case I do not need it. The admob logic is added in the firebase.ios.js and I simply found it and removed it since I do not need it.

It is **still** a problem for me since I will have to remove this manually from my plugin every single time which is not optimal.

**Comment by blaur** [comment]
@NathanWalker Sorry to be tagging you but do you have any comments on this?

**Comment by blaur** [comment]
I'm still seeing this.

If I'm not explicitly removing the admob stuff from the nativescript firebase component then the indicator in this document is not shown.
