### ISSUE TITLE
Failed to find module:"nativescript-loading-indicator"

### ISSUE THREAD

**Issue by ghost** [NathanWalker/nativescript-loading-indicator#29]
I have install nativescript-loading-indicator but after tns run android it give error module not found.

CODE:
import {LoadingIndicator} from "nativescript-loading-indicator";

private indicator: LoadingIndicator;
    public options = {
        message: 'Loading...',
        progress: 0.65,
        android: {
            indeterminate: true,
            cancelable: false,
            max: 100,
            progressNumberFormat: "%1d/%2d",
            progressPercentFormat: 0.53,
            progressStyle: 1,
            secondaryProgress: 1
        },
        ios: {
            details: "Additional detail note!",
            square: false,
            margin: 10,
            dimBackground: true,
            color: "#4B9ED6",
            // mode: // see iOS specific options below 
        }
    };

    constructor() {
        this.indicator = new LoadingIndicator();
    }

    public showLoader() {
        this.indicator.show(this.options);
    }

    public hideLoader() {
        this.indicator.hide();
    }

Any help...its urgent...please help

**Comment by sanderbos1402** [comment]
it should work, added it to project myself
dit you install it using tns add plugin ?
of course this is only available in NS so you need a service that is provider for NS with this variant.

**Comment by ghost** [comment]
Thanxx @sanderbos1402  for reply.
I had created new project than applied. Now its working on my project. But can't find the reason of not working on my previous project.

**Comment by sanderbos1402** [comment]
@SumanSingh4 sometimes if something you expect to work does not work or gives strange errors removing the platforms, hooks and node_modules directories helps.
Everything will be reinstalled fresh and often it will work then.....

**Comment by xlmnxp** [comment]
try:
```bash
tns platform clean android
tns platform clean ios
```
