### ISSUE TITLE
Support for Nativescript 3.0?

### ISSUE THREAD

**Issue by spmamidi** [NathanWalker/nativescript-loading-indicator#31]
Support for Nativescript 3.0?

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Works on Nativescript 3.0!

**Comment by zbranzov** [comment]
I will make migration PR today

**Comment by demetrio812** [comment]
Hello, any update? Does it work on NS 3.0?

**Comment by Daxito** [comment]
I also did not have any issues, still worked....

**Comment by oncul** [comment]
it doesnt work on ios but working properly on android.

**Comment by giordanocardillo** [comment]
Does it work in --release mode for you?
