### ISSUE TITLE
It breaks builds on Xcode project

### ISSUE THREAD

**Issue by brq-cr** [NathanWalker/nativescript-loading-indicator#35]
Steps to reproduce it:

`tns create HelloWorld --template nativescript-template-ng-tutorial`
`tns plugin add nativescript-loading-indicator`
`tns run ios`

**At this point it should works fine on device**

`tns prepare ios --release`

Open Xcode project inside platforms/ios/HelloWorld.xcodeproj
Run the project

**It fails at this point** - (Look attached image)

Xcode Version: 8.3.2
tns-ios@3.0.1
Nativescript 3.0.0

<img width="721" alt="screen shot 2017-05-25 at 4 02 09 pm" src="https://cloud.githubusercontent.com/assets/2147281/26472748/a9bc151e-4164-11e7-9475-fea0da32c1ce.png">

Comments:
Seems the plugin is missing **MBProgressHUD** path after build

**Comment by mvarsha** [comment]
You need to open generated platforms/ios/HelloWorld.xcworkspace to build the project.

**Comment by brq-cr** [comment]
Yes you right ! @mvarsha thank you
