### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by moritzvieli** [NathanWalker/nativescript-loading-indicator#36]
When I try to bundle my app with webpack, the following error is thrown:
ERROR in ./app.module.ngfactory.ts
Module not found: Error: Can't resolve 'nativescript-loading-indicator/index' in '/Users/xx/repo/xx/App.Client/app'
 @ ./app.module.ngfactory.ts 141:16-63
 @ ./index.aot.ts

I didn't figure out until now how to solve this problem.

**Comment by PhilipMantrov** [comment]
Same problem. Anyone fix it?

**Comment by moritzvieli** [comment]
@PhilipMantrov As a workaround, I currently create a new subfolder in the node plugin-folder called "index" and then copy the whole content of the plugin in this new folder.

**Comment by PhilipMantrov** [comment]
@moritzvieli wow, smart move. Thanks a lot.

**Comment by FriOne** [comment]
@NathanWalker could you tell if there is acceptable solution?
