### ISSUE TITLE
How to change the background color for loader(ProgressDialog) in android?

### ISSUE THREAD

**Issue by priyangamani** [NathanWalker/nativescript-loading-indicator#38]
backgroundColor: "yellow", is not working in android

**Comment by amirhoseindgr** [comment]
@priyangamani backgroundColor is an IOS specification . so you can not use this property in Android

**Comment by jofftiquez** [comment]
The [activity indicator](https://docs.nativescript.org/api-reference/classes/_ui_activity_indicator_.activityindicator#color) has a `color` property which is usable in the regular `activity-indicator`, which I believe is part of this plugin? (Correct me if Im wrong). Maybe we can add this to android options?

**Comment by VitorHFLopes** [comment]
You can now change the background color on android

```javascript
var options = {
  message: 'Loading...',
  android: {
    backgroundColor: "#4B9ED6", // color of indicator and labels
  },
  ios: {}
}
```
