### ISSUE TITLE
I'm try test this and get error

### ISSUE THREAD

**Issue by aderbas** [NathanWalker/nativescript-loading-indicator#4]
I created a simple app and try:

``` javascript
var loader = require("nativescript-loading-indicator");
loader.show();
```

I get this message error: `"Error calling module function"`

**Comment by maknz** [comment]
Stack trace?

**Comment by Onkarn92** [comment]
@maknz, I am developing app with {N}+ng2, I am currently using this plugin. But it is throwing the same error as mentioned by aderbas. The plugin is installed successfully and i didn't get any stack trace, will you please help me?
