### ISSUE TITLE
Activity Indicator is not shown

### ISSUE THREAD

**Issue by marcellodalessio** [NathanWalker/nativescript-loading-indicator#45]
I'm struggling with an issue preventing Activity Indicator being shown in my Angular-Nativescript Project.
I have a method deleteData (see below) executing a long-running task: I need to display "Activity Indicator" at the start and at the end of the method. 

The activity Indicator is not displayed, maybe because Angular doesn't refresh the UI during method execution - I tried to use also Promise and Observable but I had the same result - any idea how to solve?

----------------------------
public deleteData() {
                var loader = new LoadingIndicator();
                loader.show();
                // long running task
                this.database.executeQuery("all_customers");
                loader.hide();
}

**Comment by isaacfi** [comment]
Yoy may try to enclose your executeQuery into a setTimeout as this:

```
public deleteData() {
var loader = new LoadingIndicator();
loader.show();
setTimeout(()=>{
  // long running task
  this.database.executeQuery("all_customers");
  loader.hide();
  }, 300);
}
```

**Comment by xlmnxp** [comment]
because you're hide the `LoadingIndicator` before render processing

**Comment by amirhoseindgr** [comment]
@isaacfi  you should use hide() method after setTimeout method . the correct code is 
setTimeout(()=>{
  // long running task
  this.database.executeQuery("all_customers");
  }, 300);
 loader.hide();

**Comment by StevenLJackson1** [comment]
I would think that the correct code would move the `loader.hide()` method call inside the `setTimeout()` callback, like so:

```javascript
loader.show();
setTimeout(() => {
    // long running task
    this.database.executeQuery("all_customers");
    loader.hide();
), 300);
```
In this manner, the loader is shown, rendering can happen, long-running process kicks off, then loader is hidden when long-running process finishes.

Or am I missing something?
