### ISSUE TITLE
show and hide

### ISSUE THREAD

**Issue by JoseCortinez** [NathanWalker/nativescript-loading-indicator#50]
How could you open a loader instance on one page and close it on another?

**Comment by alemartins414** [comment]
I'm having the same problem here.. 
anyone?

**Comment by naranjja** [comment]
Yes! You can pass it on the navigation context and then hide it when you receive it:

page1.js
```js
const loader = new LoadingIndicator();
loader.show({ message: "Loading..." });
frame.topmost().navigate({
    moduleName: "page2",
    context: {
        loader,
    }
});
```

page2.js
```js
exports.onNavigatedTo = (args) => {
    const page = args.object;
    page.navigationContext.loader.hide();
}
```

**Comment by bradmartin** [comment]
@naranjja thanks for example. You just need the instance you used with `show` to `close` that same instance so passing the reference to the next page would work 💯
