### ISSUE TITLE
Support for "markingMode" flag

### ISSUE THREAD

**Issue by RinkalGohel** [NathanWalker/nativescript-loading-indicator#55]
Hi there!

Wanted to know whether your plugin will still be working fine if I add the flag of 'markingMode' set to 'none' in package.json file, as mentioned in one of the blogs of NativeScript release?

Here is the link of the blog where the reference is made for the same: https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2

Looking forward to an early reply. Thank you!

**Comment by albertobastos** [comment]
I set the markingMode flag to "none" at a v5.1.0 app that uses the LoadingIndicator extensively, and after 10 minutes navigating back and forward through multiples pages using the plugin, I saw no crashes.

Hard to tell if that's a 100% warranty, but it seems the plugin works well with that new flag enabled. And... wow, the performance increase is HUGE.

**Comment by bradmartin** [comment]
Should work fine, nothing in the code suggests an issue with markingMode GC
