### ISSUE TITLE
Can't find variable: MBProgressHUD error is crashing app

### ISSUE THREAD

**Issue by d3mac123** [NathanWalker/nativescript-loading-indicator#56]
Are you planning to make it compatible with NS 4.0? Everything was working but, since today I am getting the error:
`*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: MBProgressHUD`

which crashes the app. Full error below:
`30  0x107102ee0 vmEntryToJavaScript
file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:15:38: JS ERROR ReferenceError: Can't find variable: MBProgressHUD
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
2   anonymous@file:///app/app.js:275:22
31  0x10709c198 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*)
JavaScript stack trace:
1   show@file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:15:38
2   loadList@file:///app/flight-page.js:266:16
3   @file:///app/flight-page.js:228:17
4   invoke@file:///app/tns_modules/tns-core-modules/timer/timer.js:54:53
5   tick@file:///app/tns_modules/tns-core-modules/timer/timer.js:19:26
6   UIApplicationMain@[native code]
7   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
8   anonymous@file:///app/app.js:275:22
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  @[native code]
12  promiseReactionJob@[native code]
JavaScript error:
Aug 21	3   evaluate@[native code]
4   moduleEvaluation@:1:11
5   @:7:48
6   promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: MBProgressHUD
at
1   show@file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:15:38
2   loadList@file:///app/flight-page.js:266:16
3   @file:///app/flight-page.js:228:17
4   invoke@file:///app/tns_modules/tns-core-modules/timer/timer.js:54:53
5   tick@file:///app/tns_modules/tns-core-modules/timer/timer.js:19:26
6   UIApplicationMain@[native code]
7   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
8   anonymous@file:///app/app.js:275:22
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  @[native code]
12  promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x182052d8c 0x18120c5ec 0x106b27e60 0x106b4d2e4 0x10744f088 0x1074501b4 0x182a9f3d4 0x181ffbaa8 0x181ffb76c 0x181ffb010 0x181ff8b60 0x181f18da8 0x183efe020 0x18bf38758 0x107450044 0x10744e7a4 0x10744e26c 0x106b05630 0x<\M-b\M^@\M-&>
`

**Comment by bradmartin** [comment]
The new package will work correctly, it has been migrated to the nStudio org. https://github.com/nstudio/nativescript-loading-indicator
