### ISSUE TITLE
Loading Indicator not hiding automatically in android platform nativescript

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [NathanWalker/nativescript-loading-indicator#58]
Hai iam developing native script application for both android and ios.Iam using native script loading indicator for showing api loading process.After the response came i was hide the indicator.in ios platform the indicator was hide but android the indicator was not hiding.How to fix the issue?

**Comment by schnapzz** [comment]
Hi @ArigarasuthanRepo 
Could you provide some sample code where you're using the loading indicator?

Cheers!

**Comment by ArigarasuthanRepo** [comment]
My Loading indicator code is:

`import { LoadingIndicator } from "nativescript-loading-indicator";

export class Indicator {
    message:string;
    //loader:LoadingIndicator;
    static showIndicator(message) {
        var options = {
            message: message,
            android: {
                indeterminate: true,
                cancelable: true,
                progressStyle: 1,
                secondaryProgress: 1,
                cancelListener: function(dialog) { console.log("Loading cancelled") },
            },
            ios: {
                margin: 10,
                dimBackground: false,
                color: "#40053e", // color of indicator and labels
                userInteractionEnabled: false, // default true. Set false so that the touches will fall through it.
                hideBezel: false, // default false, can hide the surrounding bezel
                backgroundColor: "#ffffff",
            }
        };
        var loader = new LoadingIndicator();
        loader.show(options);
    }
    static hideIndicator() {
        var loader = new LoadingIndicator();
        loader.hide();
        
        

    }
}`
Iam calling this loading indictor in other class method like this:

`Indicator.showIndicator("Authenticating Please Wait.. ");`

After the api response came i was hide the indicator:

`Indicator.hideIndicator();`

But the indicator not dismissing when i call `indicator.hideIndicator()` method in android platform only.In ios platform the indicator correctly dismissed.

**Comment by manojdcoder** [comment]
By doing `var loader = new LoadingIndicator();` you are creating a new indicator every time, you were suppose to show / hide on same instance.

**Comment by ArigarasuthanRepo** [comment]
Thank you..i was fixed the issue.
