### ISSUE TITLE
ReferenceError: UIView is not defined

### ISSUE THREAD

**Issue by thukuwanjiku** [NathanWalker/nativescript-loading-indicator#59]
I'm getting this error from the ios loader options. It compiles fine when I comment out the ios options.

![screenshot_20181115-152744](https://user-images.githubusercontent.com/17809323/48552903-1dd11380-e8eb-11e8-8c37-450d4d42a00f.png)

**Comment by nginx17** [comment]
Same problem,
i was add `declare const UIView, MBProgressHUDModeDeterminate;` but still error
tns-platform-declarations are installed 

package.json 
- "tns-core-modules": "~5.0.2",
- "nativescript-loading-indicator": "^2.4.0",
- "nativescript-angular": "~7.0.0",

**Comment by thukuwanjiku** [comment]
@nginx17 I commented the UIView option, and it runs successfully on android. I have not run the same on ios so I cannot tell if commenting will break it in ios

**Comment by ibnYusrat** [comment]
> @nginx17 I commented the UIView option, and it runs successfully on android. I have not run the same on ios so I cannot tell if commenting will break it in ios

Of course it will break.

**Comment by ibnYusrat** [comment]
Still no solution to this issue?

**Comment by bradmartin** [comment]
Lots of changes recently and the plugin has been migrated to nStudio. https://github.com/nstudio/nativescript-loading-indicator

iOS and Android demos are running fine. AndroidX support and a simplified common API.

This version is deprecated now and I don't think you'll run into this issue with the `@nstudio/nativescript-loading-indicator` version. Please open an issue there if you do.
