### ISSUE TITLE
LoadingIndicator is not a function

### ISSUE THREAD

**Issue by calebeaires** [NathanWalker/nativescript-loading-indicator#6]
```
var LoadingIndicator = require("nativescript-loading-indicator");
var loader = new LoadingIndicator();
...
```

error: LoadingIndicator is not a function.

**Comment by Daxito** [comment]
@calebeaires it should be:
var loadingIndicatorModule = require("nativescript-loading-indicator");
var loader = new loadingIndicatorModule.LoadingIndicator();

**Comment by maknz** [comment]
Apologies for the incorrect documentation - @Daxito is correct.

``` js
var LoadingIndicator = require("nativescript-loading-indicator").LoadingIndicator;

var loader = new LoadingIndicator();
```

**Comment by maknz** [comment]
Fixed on master.
