### ISSUE TITLE
How to change LoadingIndicator color in Android?

### ISSUE THREAD

**Issue by Omi231** [NathanWalker/nativescript-loading-indicator#62]
In android how change how to apply styling on loading indicator. Specially loading wheel and Label color

**Comment by VitorHFLopes** [comment]
@Omi231 in the android property inside loader options you can change color property

```javascript
var options = {
  message: 'Loading...',
  android: {
    color: "#4B9ED6", // color of indicator and labels
  },
  ios: {}
}
```

For more information, check the [implementation example](https://github.com/NathanWalker/nativescript-loading-indicator/blob/master/README.md)

**Comment by Cayan** [comment]
Really bad breaking change

**Comment by NathanWalker** [comment]
Thanks
