### ISSUE TITLE
Error when not specifying any color on the options

### ISSUE THREAD

**Issue by danielgek** [NathanWalker/nativescript-loading-indicator#66]
https://github.com/NathanWalker/nativescript-loading-indicator/blob/5f0d07f291120d74140efd414262ce24a6127524/src/loading-indicator.android.ts#L51

as you can see on that line if i don't specify a text color in options it will try to user `android` as color which is not a valid color, maybe change `android` to `black` as default ?

**Comment by RacknerFrank** [comment]
@NathanWalker any fix on the horizon for this? Without passing options the app will just crash on android if you add this plugin

**Comment by 18clans** [comment]
I ran into this issue and could not figure out what it was since I did not specify a default color.  It kept throwing [Error: Invalid color: android](https://github.com/NathanWalker/nativescript-loading-indicator/issues/67)

**Comment by NathanWalker** [comment]
Thank you for reporting this @danielgek fixed in `2.5.2` now.
