### ISSUE TITLE
Archive to ITunes show MBProgressHUD no found

### ISSUE THREAD

**Issue by yclau** [NathanWalker/nativescript-loading-indicator#8]
Hello,

I was wondering if anyone else was experiencing this and has a solution. When I try to archive and publish to ITunes,it show me error below. After I remove loading-indicator and it work fine.

```
ld: warning: directory not found for option '-F/Users/bae-nb-050/Library/Developer/Xcode/DerivedData/SL-fbodsjqbjvdhcgeemiobyapkoekm/Build/Intermediates/ArchiveIntermediates/SL/BuildProductsPath/Release-iphoneos/MBProgressHUD'
    ld: framework not found MBProgressHUD
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

cocopod version : 1.0.0
nativescript version : 2.0.0 
xcode version : 7.3.1

my Podfile

```
use_frameworks!

target "SL" do
# Begin Podfile - /Applications/SL/node_modules/nativescript-loading-indicator/platforms/ios/Podfile 
 pod 'MBProgressHUD', '0.9.2'

 # End Podfile 

end
```

It works fine on a device (tns run ios) and on the simulator (tns run ios --emulator) just fail in archive .

**Comment by maknz** [comment]
Could you perhaps try a lower version of Cocoapods? I'd be interesting to see if 1.0 had any breaking changes.

**Comment by yclau** [comment]
I try to lower down Cocoapods to version 0.39.0 , still same error message in Xcode.

**Comment by yclau** [comment]
I released the Pods.framework and  MBProgressHUD.framework is missing after I build it. And I try to add back framework and give me error message : MBProgressHUD.framework : no such file or directory

**Comment by NathanWalker** [comment]
@yclau you should not be adding `frameworks` yourself or managing a Podfile in your project.

You simple follow the README here to install this plugin and use it.

**Comment by zoeitsolutions** [comment]
@NathanWalker I have the exact same problem.

I have installed the plugin and it works in my emulator.

When I try to archive my build, I get the same error he did:

```
ld: warning: directory not found for option '-F/Users/user/Library/Developer/Xcode/DerivedData/testapp-gtztwpyziibjtjcajebsjttffdkh/Build/Products/Debug-iphoneos/MBProgressHUD'
ld: framework not found MBProgressHUD
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have tried removing iOS and running tns build ios and then trying to archive from xCode.

But the build keeps failing. I am using NS 2.5 with Typescript and NG2.

**Comment by davorpeic** [comment]
Hi @zoeitsolutions , did you find solution to this? Have the same issue with building the project in xcode. I tried downgrading cocoapods from 1.2.0->1.1.0->1.0.1 that didn't help, I suspect to be some deduplication issue with the paths..

**Comment by davorpeic** [comment]
Update: you learn something every day, solution is mentioned here #21
