### ISSUE TITLE
Crash Caused By Type Error this._progressDialog.setMesssage is not a function

### ISSUE THREAD

**Issue by spstratis** [NathanWalker/nativescript-loading-indicator#9]
I've noticed that my app crashes in certain situations primarily when the app opens up from a resume event and it seems to be due to this plugin. The error is as follows:

TypeError: this._progressDialog.setMesssage is not a function
File: "/data/data/org.nativescript.CareGiver/files/app/tns_modules/nativescript-loading-indicator/src/android/progress-dialog.js, line: 24, column: 41

I can also get this to occur when using the LiveSync feature.

**Comment by Vinzius** [comment]
Same problem when running the app with Android! :( not sure how to handle the problem... :/

Btw the library works fine with iOS.

**Comment by leocaseiro** [comment]
I had the same issue. I actually remove the setMessage from `android/progress-dialog.ts:25` and `android/progress-dialog.js:24`.

I'm missing my custom Message, but works the `loading` pretty good.

**Comment by spstratis** [comment]
@leocaseiro so you just were the removal of those lines the only changes that you made? Did you need to go into the node_modules > nativescript-loading-indicator > src > android directory to make them? I'm getting a new error now after I removed the two lines you mentioned.

**Comment by leocaseiro** [comment]
Hi @spstratis, yep. That's exactly what I did. I removed from the `progress-dialog.js`:

node_modules/nativescript-loading-indicator/src/android/progress-dialog.js:11

``` javascript
            if (this._progressDialog === undefined) {
                var indeterminate = true;
                var cancelable = false;
                if (options.android) {
                    if (options.android.indeterminate !== undefined)
                        indeterminate = options.android.indeterminate;
                    if (options.android.cancelable !== undefined)
                        cancelable = options.android.cancelable;
                }
                this._progressDialog = android.app.ProgressDialog.show(context, "", options.message || "Loading...", indeterminate, cancelable);
            }
            else {
                // if (options.message)
                //     this._progressDialog.setMesssage(options.message);
                if (options.progress)
                    this._progressDialog.setProgress(options.progress);
                if (options.android) {
                    if (options.android.indeterminate)
                        this._progressDialog.setIndeterminate(true);
                    if (options.android.max)
                        this._progressDialog.setMax(options.android.max);
                    if (options.android.progressNumberFormat)
                        this._progressDialog.setProgressNumberFormat(options.android.progressNumberFormat);
                    if (options.android.progressPercentFormat)
                        this._progressDialog.setProgressPercentFormat(options.android.progressPercentFormat);
                    if (options.android.progressStyle)
                        this._progressDialog.setProgressStyle(options.android.progressStyle);
                    if (options.android.secondaryProgress)
                        this._progressDialog.setSecondaryProgress(options.android.secondaryProgress);
                }
            }
```

**Comment by spstratis** [comment]
@leocaseiro I'm assuming you removed it from the TypeScript file as well, right?

**Comment by leocaseiro** [comment]
Hi @spstratis, I didn't have to. The node_modules typescript files are ignored in my bundle. It should be ignored in your compilation as well.

**Comment by NathanWalker** [comment]
@spstratis @leocaseiro `2.1.0` published now has this fix as well as TS module fixes. 👍

**Comment by leocaseiro** [comment]
I'm so glad @NathanWalker took over this project!

@NathanWalker is a legend!
